### ISSUE TITLE
OS, machine

### ISSUE THREAD

**Issue by khayo** [wakatime/discord-wakatime#1]
I started using the discord plugin recently and I don't know if I did something wrong, but the OS and hostname are not being detected. I looked at the code to see if it passed this information at the time of the heartbeat, I also looked at the wakatime API documentation to understand where this information is collected from and I couldn't find out how it is obtained. These are screenshots of my wakatime dashboard. This problem is occurring on a Windows machine, I have not tested it in a Linux environment.

![image](https://github.com/wakatime/discord-wakatime/assets/4781909/f88c2b99-54de-47dc-af8f-dbbefd8246bf)
![image](https://github.com/wakatime/discord-wakatime/assets/4781909/fe25c0d8-32d0-4116-b273-202106d7ac39)
![image](https://github.com/wakatime/discord-wakatime/assets/4781909/a2bb8d9d-791c-47a6-9ea8-2ab1c5b0e412)

Oh, one more thing, on the wakatime website where the plugins are [listed](https://wakatime.com/discord), the link to download the plugin [files](https://github.com/wakatime/discord-wakatime/releases/latest/download/discord-wakatime.zip) shows a not found message

**Comment by alanhamlett** [comment]
We need to detect the OS and pass that along with the plugin string here:

https://github.com/wakatime/discord-wakatime/blob/439f67f488fff77c22d54c73a7f4adb04b496552/discord-wakatime.plugin.js#L69

Thanks, fixed the link.

**Comment by alanhamlett** [comment]
Detecting OS with 03a74ad83448d9fb3015cb2637ebf525fbe49207, but I think we should use [process](https://nodejs.org/api/process.html) to do it more accurately. I'll get a fix soon.

Also detecting hostname by reading `/etc/hostname` on Linux. For Windows and Mac I'll have to find another way to detect hostname.

**Comment by alanhamlett** [comment]
Fixed in v1.0.1.
