### ISSUE TITLE
Make A Plugin For Vencord Too

### ISSUE THREAD

**Issue by itsmechinmoy** [wakatime/discord-wakatime#5]

**Comment by alanhamlett** [comment]
https://github.com/NeonGamerBot-QK/Vencord-Plugins

**Comment by itsmechinmoy** [comment]
> https://github.com/NeonGamerBot-QK/Vencord-Plugins

How to add it to vencord do uk?

**Comment by alanhamlett** [comment]
Install instructions are in that repo.

**Comment by itsmechinmoy** [comment]
ok
